const constantNotify = {
  ACCESS_TOKEN:
    "76188abd0b1d34f4aa824b8b2c597fe2eb68a805fe90b5906ec0d18bcd6e2380",
  REFRESH_TOKEN:
    "a7555e4b4b7f67427d2e804d539ec369fd36af46b700907d003d524422749829",
  TOKEN_TIME_LIFE: "3d",
  REFRESH_TOKEN_TIME_LIFE: "7d",
  VALIDATE_ACCOUNT:
    "The account must contain lowercase, uppercase, special characters and numbers",
  VALIDATE_EMAIL: "Please enter correct Email format",
  VALIDATE_PHONE_NUMBER: "Please enter correct phoneNumber format",
  VALIDATE_PASSWORD:
    "Password consists of 8 digits including uppercase, lowercase letters, numbers",
  VALIDATE_IMAGE: "Please choose an image",
  ERROR: "Error! An error occurred. Please try again later",
  DB_ERROR: "There was a DB connection error",
  INVALID: "unauthenticated",
  ALREADY_EXIST: "already exists",
  ADD_DATA_SUCCESS: "Add Success",
  ADD_DATA_FAILED: "Add Fail",
  ACCOUNT_NOTFOUND: "Incorrect account",
  EMAIL_NOTFOUND: "Email is not correct",
  ACTIVE_FAILD: "Account not activated",
  PASS_FAILD: "Incorrect password",
  ACCOUNT_NOTEMPTY: "Account cannot be empty",
  EMAIL_NOTEMPTY: "Email cannot be empty",
  PASSWORD_NOTEMPTY: "Password can not be blank",
  DELETE_DATA_SUCCESS: "Delete successfully",
  UPDATE_DATA_SUCCESS: "Update successful",
  UPDATE_DATA_FAILED: "Update fail",
  MOVE_COURSE_SUCCESS: "Move course successful",
  MOVE_COURSE_FAILD: "Move course faild",
  NOT_EXITS: "does not exist",
  VALIDATE_FILE_SIZE: "File size is more than 2MB",
  VALIDATE_FILE: "Please select the file to upload",
  DATALIMIT1000: "Data over 1000 . limit",
  NOT_ACTIVE: "not activated",
  IS_WRONG: "wrong",
  SEND_SUCCESS: "submitted successfully",
  CLASS_SCHEDULE: "Duplicate class schedule",
  NO_DATA: "No data",
  NOT_EMPTY: "do not leave blank",
  NOT_AUTH: "User not authenticated",
  VERIFY_SUCCESS: "Verify success",
};

module.exports = constantNotify;
